### PR TITLE
Add DragonFlyBSD support

### PR DESCRIPTION
**Pull request by daftaupe**

### CODE REVIEW

**Comment by daftaupe** [comment]
Hello,

I'm just wondering if there's anything preventing from adding this ?

Regards,

**Comment by cznic** [comment]
> I'm just wondering if there's anything preventing from adding this ?

No, sorry, I'm aware of the PR just since few minutes ago. I may have forgotten, I may have accidentally deleted the mail, I don't know.

**Comment by cznic** [comment]
Thank you for the PR!

**Comment by daftaupe** [comment]
@cznic, no worries, I was just curious if I had to change something maybe.
Thanks for your reactivity :)

**Pull request merged**
